on: 
  release:
    types: [created]

jobs:
  releases:
    name: release binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:  
          - goarch: "386"
            goos: darwin
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.19
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64