on: 
  release:
    types: [created]

jobs:
  releases:
    name: release binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, freebsd, openbsd]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: freebsd
          - goarch: arm64
            goos: openbsd
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.19
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
