on: 
  release:
    types: [created]

jobs:
  releases:
    name: release binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, freebsd, openbsd]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: freebsd
          - goarch: arm64
            goos: openbsd
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Build and release
      uses: wangyoucao577/go-release-action@v1.19
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        build_command: "make build"
        pre_command: "make frontend"
